# -*- coding: utf-8 -*-
"""MTCNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LlIeoRmQKlMke7UoJgnRyoSS_UT16TsS
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive

!pip install facenet_pytorch

from facenet_pytorch.models.inception_resnet_v1 import get_torch_home
torch_home = get_torch_home()

import os
from facenet_pytorch import MTCNN
import cv2
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt
from tqdm.notebook import tqdm

MANIPULATED_VIDEOS_PATH = '/gdrive/My Drive/Manipulated Videos 000-999'
MANIPULATED_FACE_CROPS_PATH = '/gdrive/My Drive/0-999_Manipulated_Face_Crops'

def create_face_crops(path, filename):
  mtcnn = MTCNN(margin=20, post_process=False, device='cuda:0')
  # Load a video
  v_cap = cv2.VideoCapture(os.path.join(path, filename))
  v_len = int(v_cap.get(cv2.CAP_PROP_FRAME_COUNT))
  # Loop through video
  batch_size = 8
  frames = []
  faces = []
  for _ in tqdm(range(v_len)):
    # Load frame
    success, frame = v_cap.read()
    if not success:
        continue
    # Add to batch
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    frames.append(Image.fromarray(frame))
    # When batch is full, detect faces and reset batch list
    if len(frames) >= batch_size:
        save_paths = [f'{MANIPULATED_FACE_CROPS_PATH}/{filename}_{i}.jpg' for i in range(len(frames))]
        faces.extend(mtcnn(frames, save_path=save_paths))
        frames = []

import torch
for dirname, _, filenames in os.walk(MANIPULATED_VIDEOS_PATH):
  for filename in filenames:
    create_face_crops(MANIPULATED_VIDEOS_PATH, filename)

create_face_crops(MANIPULATED_VIDEOS_PATH, '549_531.mp4')

list1 = []
for i in range(1000):
  list1.append(i)

list2 = []
for dirname, _, filenames in os.walk(MANIPULATED_FACE_CROPS_PATH):
  for filename in filenames:
    if int(filename[0:3]) not in list2:
      list2.append(int(filename[0:3]))
print(len(list2))

len(list(set(list1) - set(list2)))

for dirname, _, filenames in os.walk(MANIPULATED_FACE_CROPS_PATH):
  print(len(filenames))